#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

du - Plugin to monitor the size of files

=head1 CONFIGURATION

The following environment variables are used

 files       - Files to check

Configuration example

 [du]
  env.files /var/log/syslog /var/log/nginx/error.log

=head1 AUTHOR

Copyright (C) 2013 Thomas Heidrich

=head1 LICENSE

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; version 2 dated June,
1991.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

=head1 MAGIC MARKERS

 #%# family=manual

=cut

if [ "$1" = "config" ]; then
    echo 'graph_args --base 1024 -l 0'
    echo 'graph_title File sizes'
    echo 'graph_vlabel bytes'
    echo 'graph_category disk'
    echo 'graph_info This graph shows file size statistics.'
    for file in $files; do
	directory=`expr $directory + 1`
	echo "directory$directory.label $file"
	echo "directory$directory.info Files size statistics for $file."
    done
    exit 0
fi

for file in $files; do
    export directory=`expr $directory + 1`
    echo -n "directory$directory.value "
    du -sb ${file} | cut -f1
done
